Add Behat test linting to CI workflow
This adds two checks to the quality checks in the CI.

1. Check that all test files are named using lowercase kebab-case
containing only letters and numbers. This ensures consistent filenaming.

2. Run the features themselves through Cucumber Linter which provides
common feedback about how to structure a test file and make it readable.

Logic is implemented to only run this on files that are added or
modified (skipping deleted files) because we have a lot of existing
tests and we don't want to have complaints about all of them for every
PR that doesn't touch them.

diff --git a/.github/workflows/qualityChecks.yml b/.github/workflows/qualityChecks.yml
--- a/.github/workflows/qualityChecks.yml
+++ b/.github/workflows/qualityChecks.yml
@@ -179,3 +179,47 @@ jobs:
     steps:
       - uses: actions/checkout@v3
       - uses: streetsidesoftware/cspell-action@v5
+
+  behat-linting:
+    name: Behat Linting
+    runs-on: ubuntu-22.04
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v3
+
+      - name: Install developer tooling
+        run: composer install --no-interaction --no-progress --working-dir=tests
+
+      - name: Find changed test files
+        run: |
+          git fetch origin $BRANCH_NAME
+          # We change the way we create the TEST_FILES env in the GITHUB_ENV file depending on whether we actually have
+          # test files that were changed in this PR. This is needed to avoid the TEST_FILES variable from containing a
+          # single blank line in case no files are changed.
+          TEST_FILES=`git diff --name-only --diff-filter=d origin/$BRANCH_NAME..HEAD -- 'tests/behat/features/capabilities/*.feature'`
+          if [ $TEST_FILES == '' ]; then
+            echo 'TEST_FILES=' >> $GITHUB_ENV
+          else
+            {
+              echo 'TEST_FILES<<EOF'
+              echo $TEST_FILES
+              echo EOF
+            } >> "$GITHUB_ENV"
+          fi
+        env:
+          BRANCH_NAME: ${{ github.base_ref || github.ref_name }}
+
+      - name: Ensure behat folder and filenames are kebab-case
+        if: ${{ env.TEST_FILES != '' }}
+        run: |
+          # We must invert the exit code because we want to have no matches, but grep treats no matches as failure.
+          ! MISNAMED_FILES=`grep -v -E '^([a-z\-]+\/)+[a-z0-9\-]+\.feature$' <<<"$TEST_FILES"`
+          EXIT_CODE=$?
+          while read -r file; do
+            echo "::error file=$file::File and folder names for Behat tests must be kebab-case and alphanumeric."
+          done <<< "$MISNAMED_FILES"
+          exit $EXIT_CODE
+
+      - name: Lint modified test files
+        if:  ${{ env.TEST_FILES != '' }}
+        run: xargs tests/vendor/bin/cucumber-linter <<<"$TEST_FILES"
